spring:
  application:
    name: dubbo-other
  cloud:
    nacos:
      config:
        server-addr: ${VM_IP:127.0.0.1}:8848
        namespace: 79ec2bf2-77da-40a4-a877-a05dcadea95d
  config:
    import:
      - optional:nacos:dubbo-other.yaml?group=CLOUD_GROUP  # 监听 DEFAULT_GROUP:test.yml
apisix:
  url: http://192.168.112.130:9180
  upstream-id: 123