spring:
  application:
    name: dubbo-provider
  cloud:
    nacos:
      config:
        server-addr: 172.16.6.77:8748
        namespace: 0825b7fd-30bc-4df8-976f-eccce616b3e1
    sentinel:
      transport:
        port: 8710
        dashboard: localhost:8080
  config:
    import:
      - optional:nacos:dubbo-provider.yaml?group=CLOUD_GROUP  # 监听 DEFAULT_GROUP:test.yml
dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://172.16.6.77:8748?namespace=${spring.cloud.nacos.config.namespace}
shenyu:
  client:
    registerType: nacos #zookeeper #etcd #nacos #consul
    serverLists: ${spring.cloud.nacos.config.server-addr} #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      contextPath: /demo
      appName: dubbo-provider
      port: ${server.port}
      isFull: true
      nacosNameSpace: ${spring.cloud.nacos.config.namespace}