spring:
  application:
    name: dubbo-provider
  cloud:
    nacos:
      config:
        server-addr: 172.16.6.77:8848
        namespace: 79ec2bf2-77da-40a4-a877-a05dcadea95d
    sentinel:
      transport:
        port: 8710
        dashboard: localhost:8080
  config:
    import:
      - optional:nacos:dubbo-provider.yaml?group=DUBBO_MYSQL  # 监听 DEFAULT_GROUP:test.yml
dubbo:
  application:
    name: dubbo_provider
  protocol:
    name: tri
    port: -1
  registry:
    address: nacos://172.16.6.77:8848