spring:
  application:
    name: dubbo-provider
  cloud:
    nacos:
      config:
        server-addr: 172.16.6.77:8848
        namespace: 79ec2bf2-77da-40a4-a877-a05dcadea95d
    sentinel:
      transport:
        port: 8710
        dashboard: localhost:8080
  config:
    import:
      - optional:nacos:dubbo-provider.yaml?group=CLOUD_GROUP  # 监听 DEFAULT_GROUP:test.yml