spring:
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      config:
        server-addr: ${VM_IP:127.0.0.1}:8848
        namespace: 79ec2bf2-77da-40a4-a877-a05dcadea95d
  config:
    import:
      - optional:nacos:dubbo-consumer.yaml?group=CLOUD_GROUP  # 监听 DEFAULT_GROUP:test.yml
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'dubbo-consumer'
      paths-to-match: '/**'
      packages-to-scan: qtx.dubbo
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
rocketmq:
  endpoint: 192.168.77.130:8081