spring:
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      config:
        server-addr: ${nacos_ip:127.0.0.1}:8848
        namespace: ae54b0ac-6f79-4a96-8d0b-40ab6fbde508
  config:
    import:
      - optional:nacos:dubbo-consumer.yaml?group=CLOUD_GROUP  # 监听 DEFAULT_GROUP:test.yml
apisix:
  upstream-id: 456